# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
title: Joshua Carley
email: joshuacarley@gmail.com
description: This is the website of Joshua Carley 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshuacarley.com" # the base hostname & protocol for your site
markdown: kramdown
